
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -  id: mypy
       args: [ "--config-file", "./mypy.ini" ]
       additional_dependencies:
         - Django~=6.0.5
         - black~=26.3.1
         - mypy~=2.1.0
         - django-stubs[compatible-mypy]~=6.0.4
         - pre-commit~=4.6.0
         - psycopg2~=2.9.12; sys_platform == "linux"
         - psycopg2-binary~=2.9.12; sys_platform != "linux"