
repos:
-   repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev:  v2.0.0 # Use the sha / tag you want to point at
    hooks:
    -  id: mypy
       args: [ "--config-file", "./mypy.ini" ]
       additional_dependencies:
         - Django~=6.0.5
         - black~=26.5.1
         - mypy~=2.0.0
         - django-stubs[compatible-mypy]~=6.0.4
         - pre-commit~=4.6.0
         - psycopg2~=2.9.12; sys_platform == "linux"
         - psycopg2-binary~=2.9.12; sys_platform != "linux"