# Generated by Django 6.0.6 on 2026-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
